= dev_env

My dev environment for linux.

== Tools used

=== Tool to manage the configuration

Vcsh is used do manage a git repository in my home directory.

* VCSH : https://github.com/RichiH/vcsh

==== How to init this repository on a new machine

. Install vcsh `apt install vcsh` on a Ubuntu linux
. `vcsh init dev_env`
. `vcsh dev_env remote add origin https://github.com/fboulay/dev_env`
. `vcsh dev_env pull`


=== Configuration files

The repository contains my configuration for the following apps:

* Antigen : https://github.com/zsh-users/antigen
* zsh
* bash
* vim
* git
* Atom : https://atom.io/
* Albert : https://github.com/ManuelSchneid3r/albert
* CopyQ : https://hluk.github.io/CopyQ/
* Variety : http://peterlevi.com/variety/
* gnome terminal
* meld
* Maven
* Shutter : http://shutter-project.org/
* Visual Studio Code : https://code.visualstudio.com/
* Espanso: https://espanso.org/
* Conky


== How to use on a new machine

=== git

To use git, create a file in your home directory called `.gitconfig-local`. This file should contains git user configuration, for instance:

```
[user]
    name = foo
    mail = foo@gmail.com
```

== Other manual installation

=== Droidcam

To use the smartphone as a webcam https://www.dev47apps.com/droidcam/linux/

=== OBS

To have OBS work, we have to install a plugin to create a virtual camera. OBS plugin to have a sink to v4l2

This article explains how to install the plugin https://blog.jbrains.ca/permalink/using-obs-studio-as-a-virtual-cam-on-linux

The repository of the plugin is https://github.com/CatxFish/obs-v4l2sink




== Licence

link:LICENCE[MIT]
