;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; THIS FILE IS GENERATED    ;
;; DO NOT EDIT THIS FILE     ;
;; edit `config.org` instead ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(setq user-full-name "Florian Boulay"
      user-mail-address "florian@boulay.eu")

(doom-load-envvars-file "~/.doom.d/custom.env")

(setq doom-theme 'doom-vibrant)
(setq doom-themes-treemacs-theme "doom-colors")

(setq doom-font (font-spec :family "Fira Code" :size 12.0)
      doom-variable-pitch-font (font-spec :family "Noto Sans" :size 13.0 :weight 'normal) ; inherits `doom-font''s :size
      doom-symbol-font (font-spec :family "Fira Code" :size 12.0)
      doom-big-font (font-spec :family "Fira Code" :size 20.0))

(setq doom-themes-treemacs-enable-variable-pitch nil)

(setq display-line-numbers-type 'relative)

;; Delete files by moving them to trash.
(setq-default delete-by-moving-to-trash t
              trash-directory nil) ;; Use freedesktop.org trashcan

(+global-word-wrap-mode +1)

; Use bash as default shell
(setq shell-file-name (executable-find "bash"))
; Use fish in vterm
(setq-default vterm-shell "/bin/fish")
(setq-default explicit-shell-file-name "/bin/fish")

(use-package! evil
  :custom
  (evil-want-fine-undo t)         ;; By default while in insert all changes are one big blob
  (evil-kill-on-visual-paste nil) ;; Do not put overiden text in clipbard
  (evil-move-beyond-eol t)        ;; Allow cursor to pass the end of line, especially when moving forward sexp
  :config
  (fset 'evil-visual-update-x-selection 'ignore)        ;; Do not put selected text in clipboard
  (setq evil-normal-state-tag   (propertize "[Normal]")
        evil-emacs-state-tag    (propertize "[Emacs]" )
        evil-insert-state-tag   (propertize "[Insert]")
        evil-motion-state-tag   (propertize "[Motion]")
        evil-visual-state-tag   (propertize "[Visual]")
        evil-operator-state-tag (propertize "[Operator]")))

(map! :after evil
      :map evil-eval-map
      "C-c" nil)

;; Show list of buffers when splitting.
(defadvice! prompt-for-buffer (&rest _)
  :after '(evil-window-split evil-window-vsplit)
  (projectile-find-file))

(use-package! evil-smartparens
  :after evil
  :hook
  (smartparens-enabled . evil-smartparens-mode)
  (smartparens-enabled . smartparens-strict-mode))

(use-package! evil-matchit
  :after evil-easymotion
  :config
  (global-evil-matchit-mode 1))

(defun fb/better-evil-jump-item ()
  "Try to be a better `evil-jump-item`."
  (interactive)
  ;; Special case if selected region is active
  (if mark-active
      ;; (call-interactively 'evilmi-jump-items)                 ;; → not working
      (setq unread-command-events (listify-key-sequence "%"))    ;; → working as expected, the key `%` is bound to evilmi-jump-items
    ;; when no region selected, it is trickier to call the right `jump-item` function
    (let (
          ;; (in-string (bounds-of-thing-at-point 'word))
          (in-sexp (bounds-of-thing-at-point 'sexp))
          (is-punctuation (or (= 91 (char-after)) ;; [
                              (= 93 (char-after)) ;; ]
                              (= 41 (char-after)) ;; )
                              (= 40 (char-after)) ;; (
                              (= 34 (char-after)) ; "
                              (= ?{ (char-after))
                              (= ?} (char-after))
                              (= ?' (char-after))))
          (point-is-space (= 32 (char-after)))
          (point-is-double-quote (= 34 (char-after))))
      (cond
       ;; ((and (not is-punctuation) in-string) (goto-char (1- (car in-string))))
       (is-punctuation (evilmi-jump-items))
       ;; ((and (not is-punctuation) in-sexp) (goto-char (1- (car in-sexp))))
       ((and (not is-punctuation) in-sexp) (progn
                                             (sp-beginning-of-sexp)
                                             (backward-char)))
       (t (evil-jump-item))))))

(map! :after evil-matchit
      :map  evil-matchit-mode-map
      :desc "Better jump item"
      :m [tab] 'fb/better-evil-jump-item)

(use-package! treemacs
  :custom
  ;; (treemacs-text-scale -1) ;; disabled because in the Flycheck LSP window, the font was too small
  (treemacs-recenter-after-file-follow 'on-distance)
  (treemacs-recenter-distance 0.2)
  (treemacs-collapse-dirs 3)
  :config
  (treemacs-follow-mode 1)
  (treemacs-indent-guide-mode 1)
  (treemacs-fringe-indicator-mode 'only-when-focused))

;; (add-hook 'window-setup-hook #'treemacs 'append) ;; used for treemacs to appear in Emacs clients

(map! :leader
      :desc "Treemacs focus"
      "\\" #'treemacs-select-window)

;; Customize undo-fu package: more memory and fine grained undo in insert mode
;; Increase undo history limits even more
(use-package! undo-fu
  :custom
  (undo-limit 10000000)      ;; 1MB   (default is 160kB, Doom's default is 400kB)
  (undo-strong-limit 100000000)  ;; 100MB (default is 240kB, Doom's default is 3MB)
  (undo-outer-limit  1000000000)) ;; 1GB   (default is 24MB,  Doom's default is 48MB)

(use-package! ispell
  :custom
  (ispell-dictionary "en_US,fr_FR")
  :config
  (ispell-set-spellchecker-params)
  (ispell-hunspell-add-multi-dic "en_US,fr_FR"))

;; found here https://github.com/seagle0128/doom-modeline/issues/207
(defun fb/setup-doom-modeline-evil-states-color () ;; setting up colors for Evil mode
  (interactive)
  (set-face-attribute 'doom-modeline-evil-normal-state nil   :background "green"  :foreground "black")
  (set-face-attribute 'doom-modeline-evil-emacs-state nil    :background "orange" :foreground "black")
  (set-face-attribute 'doom-modeline-evil-insert-state nil   :background "red"    :foreground "white")
  (set-face-attribute 'doom-modeline-evil-motion-state nil   :background "blue"   :foreground "white")
  (set-face-attribute 'doom-modeline-evil-visual-state nil   :background "gray80" :foreground "black")
  (set-face-attribute 'doom-modeline-evil-operator-state nil :background "purple"))

(use-package! doom-modeline
  :hook
  (doom-modeline-mode . fb/setup-doom-modeline-evil-states-color)
  :custom
  (doom-modeline-major-mode-icon t)
  (doom-modeline-major-mode-color-icon t)
  (doom-modeline-buffer-state-icon t)
  (doom-modeline-vcs-max-length 30)
  (doom-modeline-modal-icon nil)
  (doom-modeline-buffer-file-name-style 'truncate-upto-project)
  (doom-modeline-persp-name t))

;; Allow which-key to have a good size see https://github.com/doomemacs/doomemacs/issues/5622
(use-package! which-key
  :custom
  (which-key-allow-imprecise-window-fit nil)
  ;; set suggestions to appear faster
  (which-key-idle-delay 0.5) ;; Default is 1.0
  (which-key-idle-secondary-delay 0.05)
  (which-key-max-description-length 35)
  (which-key-allow-multiple-replacements t)
  (which-key-use-C-h-commands t)
  :config
  ;; Replace evil and evilem words with unicode characters
  (pushnew! which-key-replacement-alist
            '(("" . "\\`+?evil[-:]?\\(?:a-\\)?\\(.*\\)") . (nil . "🅔.\\1"))
            '(("\\`g s" . "\\`evilem--?motion-\\(.*\\)") . (nil . "Ⓔ·\\1"))))

(use-package! orderless
  :custom
  ;; Alow to match spaces using a backslash to escape them, eg `ch\ ' matches the characters `ch' followed by a space
  (orderless-component-separator #'orderless-escapable-split-on-space)
  ;; Allow search result to be more fuzzy
  (orderless-matching-styles '(orderless-literal orderless-regexp orderless-initialism)))

(defun fb/projectile-project-name (project-root)
  "Allow to name projects for projectile and workspaces (persp) using a merge of the 2 parent directories."
  (let ((last-part  (car (last (butlast  (file-name-split (file-name-as-directory project-root))))))
        (previous-last-part (car (last (butlast (butlast  (file-name-split (file-name-as-directory project-root))))))))
    (if (string= "workspace" previous-last-part)
        last-part
      (concat previous-last-part "-" last-part))))

;; Specific config for projectile not to index home directory
(use-package! projectile
  :custom
  (projectile-create-missing-test-files t)
  (projectile-project-name-function 'fb/projectile-project-name)
  :config
  (setq projectile-project-search-path
        '("~/workspace"
          "~/.doom.d"))) ;; ("dir" . depth)

(map!
 :after smartparens
 :map smartparens-mode-map
 :ni "C-M-<" #'sp-backward-barf-sexp
 :ni "C-M->" #'sp-forward-barf-sexp
 :ni "C->" #'sp-forward-slurp-sexp
 :ni "C-<" #'sp-backward-slurp-sexp)

(use-package! avy
  :defer t
  :custom
  (avy-single-candidate-jump t))

(use-package! nav-flash
  :defer t
  :custom
  (nav-flash-delay 1.0))

(require 'json)
(defun fb/emacs-everywhere--app-info-linux-hyprland ()
  "Return information on the current active window, on a Linux Hyprland session."
  (let* ((json-string (emacs-everywhere--call "hyprctl" "-j" "activewindow"))
         (json-object (json-read-from-string json-string))
         (window-id (cdr (assoc 'address json-object)))
         (app-name (cdr (assoc 'class json-object)))
         (window-title (cdr (assoc 'title json-object)))
         (window-geometry (list (aref (cdr (assoc 'at json-object)) 0)
                                (aref (cdr (assoc 'at json-object)) 1)
                                (aref (cdr (assoc 'size json-object)) 0)
                                (aref (cdr (assoc 'size json-object)) 1))))
    (make-emacs-everywhere-app
     :id window-id
     :class app-name
     :title window-title
     :geometry window-geometry)))

(use-package! emacs-everywhere
  :defer t
  :config
  (setq emacs-everywhere-window-focus-command (list "hyprctl" "dispatch" "focuswindow" "address:%w"))
  (setq emacs-everywhere-app-info-function #'fb/emacs-everywhere--app-info-linux-hyprland))

(map! :after company
      :map company-active-map
      ;; "<tab>" #'company-complete
      "<tab>" nil
      "TAB" #'company-complete
      "RET" nil
      "<return>" nil)

(map! :after corfu
      ;; :map corfu-map
      ;; "<tab>" #'company-complete
      ;; "<tab>" nil
      ;; "TAB" #'company-complete
      ;; "RET" nil
      ;; "<return>" nil
                    )

(use-package! clojure-mode
  :defer t
  :config
  (setq clojure-toplevel-inside-comment-form t))

(map! :after clojure-mode
  :map clojure-mode-map
  "C-c C-r ESC" nil) ;; By default it was bound to convert the collection to a vector

(use-package! clj-refactor
  :defer t
  :config
  (setq cljr-add-ns-to-blank-clj-files nil))

(setq fb/clojure-default-lib
      "(require 'bogus.core)
       (require 'hashp.core)
       (require 'sc.api)")

(setq fb/clojurescript-default-lib
      "(require 'hashp.core)
       (require 'sc.api)")

(defun fb/cider-default-forms ()
  (pcase (cider-repl-type-for-buffer)
    ('clj (cider-nrepl-sync-request:eval
           fb/clojure-default-lib
           nil (cider-current-ns)))
    ('cljs (cider-nrepl-sync-request:eval
            fb/clojurescript-default-lib
            nil (cider-current-ns))))
  ;; (when (eq 'clj (cider-repl-type-for-buffer))
  ;;   (cider-nrepl-sync-request:eval
  ;;    fb/clojure-default-lib
  ;;    nil (cider-current-ns)))
  )

(use-package! cider
  :defer t
  :hook
  (cider-stacktrace-mode . (lambda ()
                             (turn-off-evil-matchit-mode)))
  :custom
  (cider-eval-result-duration 'change)
  (cider-eval-spinner-type 'progress-bar-filled)
  (cider-save-file-on-load t)
  (cider-test-show-report-on-success t)
  (cider-enrich-classpath t)
  (cider-enable-nrepl-jvmti-agent t)
  (cider-use-xref nil)
  :config
  (setq cider-clojure-cli-parameters (concat cider-clojure-cli-parameters " -A:user:dev:test -J-Xms1G -J-Xmx20G"))
  (setq cider-lein-parameters (concat cider-lein-parameters " update-in :jvm-opts conj '\"-Xms1G\"' '\"-Xmx20G\"' --"))
  (set-popup-rule! "^\\*cider-repl" :height 0.36 :ttl nil :quit t)
  :init
  ;; (add-hook 'cider-before-eval-hook #'fb/cider-default-forms)
                                                             )

(use-package! cider-eval-sexp-fu
  :after cider
  :custom
  (eval-sexp-fu-flash-duration 0.5)
  (eval-sexp-fu-flash-error-duration 0.8))

(use-package! lsp-mode
  :defer t
  :custom
  (lsp-headerline-breadcrumb-enable t)
  (lsp-semantic-tokens-enable t)
  (lsp-lens-place-position 'above-line)
  ;; (lsp-inlay-hint-enable t)
  :custom-face
  ;; this is to not be in conflict with visual mode
  ;; (set-face-attribute 'lsp-face-highlight-textual nil :foreground nil :background nil :weight 'bold :underline "#51afef")
  (lsp-face-highlight-textual ((t (:foreground nil :background nil :weight bold :underline "#51afef"))))
  )

;; Filter LSP errors to only display errors for current project. Display the window with `SPC c X`
(after! (:and treemacs lsp-mode)
  (setq lsp-treemacs-error-list-current-project-only t))

(use-package! lsp-java
  :defer t
  :custom
  (lsp-java-content-provider-preferred "fernflower"))

(use-package! lsp-ui
  :custom
  (lsp-ui-doc-show-with-cursor t)
  (lsp-ui-doc-position 'top)
  (lsp-ui-doc-max-height 15))

;; create a global minor mode for `magit-wip-mode`
(define-globalized-minor-mode global-wip-mode magit-wip-mode
  (lambda ()
    (magit-wip-mode 1)))

;; Disabled for now, as I can't start Emacs with the forge package....
;; (use-package! magit
;;   :defer t
;;   :custom
;;   (magit-save-repository-buffers 'dontask)
;;   :config
;;   (add-to-list 'forge-alist '("gitlab.oscaroad.com" "gitlab.oscaroad.com/api/v4" "gitlab.oscaroad.com" forge-gitlab-repository)))

;; save in the local git repository, every version of files
;; (after! (:and magit vc)
;;   (global-wip-mode 1))

;; Allow to see TODO in the git status window
(after! (:and magit magit-todos)
  (magit-todos-mode))

(map! :after magit
       :leader
       :desc "Magit WIP current branch"
       "g w" #'magit-wip-log-current
       :desc "Magit WIP"
       "g W" #'magit-wip-log
       :desc "Magit edit thing"
       "g e" #'magit-edit-thing
       :desc "Start code review"
       "g z" #'+magit/start-code-review)

(use-package! difftastic
  :demand t
  :bind (:map magit-blame-read-only-mode-map
         ("D" . difftastic-magit-show)
         ("S" . difftastic-magit-show))
  :config
  (eval-after-load 'magit-diff
    '(transient-append-suffix 'magit-diff '(-1 -1)
       [("D" "Difftastic diff (dwim)" difftastic-magit-diff)
        ("S" "Difftastic show" difftastic-magit-show)])))

(map! :after difftastic
      :leader
      :desc "Difftastic current file"
      "g d" (lambda () (interactive) (difftastic-git-diff-range  "HEAD^..HEAD" nil (list (buffer-file-name)))))

(use-package! git-link
  :after magit)

(map! :after git-link
      :leader
      :desc "Link to current line"
      "g k" #'git-link)

;; (use-package! codeium
;;   :defer t
;;   :hook
;;   (clojure-mode . (lambda () (setq-local completion-at-point-functions '(codeium-completion-at-point))))
;;   :config
;;   (setq codeium/metadata/api_key (auth-source-pick-first-password :host "codeium.com"))
;;   )

(use-package! vterm
  :defer t
  :config
  (set-popup-rule! "^\\*doom:vterm" :height 0.36 :quit t))

(use-package! agent-shell
  :defer t
  :config
  (setq agent-shell-opencode-authentication
        (agent-shell-opencode-make-authentication :none t))
  (setq agent-shell-anthropic-claude-environment
        (agent-shell-make-environment-variables
         "ANTHROPIC_API_KEY" (auth-source-pick-first-password :host "claude.ai")))
  (setq agent-shell-anthropic-authentication
        (agent-shell-anthropic-make-authentication :api-key (auth-source-pick-first-password :host "claude.ai"))))

(map! :leader
      :desc "Open agent shell"
      "l a" #'agent-shell)

(map! :mode agent-shell-mode
      :n "g j" #'agent-shell-next-item
      :n "g k" #'agent-shell-previous-item)

(use-package! org
  :defer t
  :custom
  (org-log-done 'time)
  (org-hide-emphasis-markers t)
  ;; (org-ellipsis " ▼")
  (org-edit-src-content-indentation 0)
  :config
  ;; set height of headings in org documents
  (dolist (face '((org-level-1 . 1.4)
                  (org-level-2 . 1.3)
                  (org-level-3 . 1.2)
                  (org-level-4 . 1.1)
                  (org-level-5 . 1.1)
                  (org-level-6 . 1.1)
                  (org-level-7 . 1.1)
                  (org-level-8 . 1.1)))
    (set-face-attribute (car face) nil :weight 'normal :height (cdr face)))

  ;; ;; make sure certain org faces use the fixed-pitch face when variable-pitch-mode is on
  ;; (custom-set-faces!
  ;;   '(line-number :inherit fixed-pitch)
  ;;   '(line-number-current-line :inherit fixed-pitch)
  ;;   ;; '(org-indent :inherit fixed-pitch)
  ;;   '(org-block :inherit fixed-pitch :foreground nil)
  ;;   '(org-table :inherit fixed-pitch)
  ;;   '(org-formula :inherit fixed-pitch)
  ;;   '(org-checkbox :inherit fixed-pitch)
  ;;   '(org-code :inherit (shadow fixed-pitch))
  ;;   '(org-verbatim :inherit (shadow fixed-pitch) :background "#1f2329")
  ;;   '(org-special-keyword :inherit (font-lock-comment-face fixed-pitch))
  ;;   '(org-meta-line :inherit (font-lock-comment-face fixed-pitch)))
                                                                   )

;; (defun fb/faces-for-variable-pitch-mode (&rest args)
;;   "Specify which face the variable pitch mode should not override"
;;     (set-face-attribute 'line-number nil :inherit 'fixed-pitch)
;;     (set-face-attribute 'line-number-current-line nil :inherit 'fixed-pitch)
;;     (set-face-attribute 'org-indent nil :inherit 'fixed-pitch)
;;     (set-face-attribute 'org-block nil :inherit 'fixed-pitch :foreground nil)
;;     (set-face-attribute 'org-table nil :inherit 'fixed-pitch)
;;     (set-face-attribute 'org-formula nil :inherit 'fixed-pitch)
;;     (set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch)
;;     (set-face-attribute 'org-code nil :inherit '(shadow fixed-pitch))
;;     (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch) :background "#1f2329")
;;     (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
;;     (set-face-attribute 'org-meja-line nil :inherit '(font-lock-comment-face fixed-pitch))
                                                                  ;; )

;; (advice-add 'variable-pitch-mode :after #'fb/faces-for-variable-pitch-mode)

;; (use-package! org-tempo
;;     :after org
;;     :init
;;     (add-to-list 'org-structure-template-alist
;;                  '("el" . "src emacs-lisp")))

(use-package! org-agenda
  :after org
  :custom
  (org-agenda-start-with-log-mode t)
  (org-agenda-files '("~/org-nc/" "~/org-nc/roam")))

(use-package! org-roam
  :after org
  :custom
  (org-roam-directory "~/org-nc/roam/"))

(defun fb/variable-pitch-faces (&rest args)
  "Define faces that should stay fixed when using variable-pitch-mode"
  (if buffer-face-mode
      ;; we are going from fixed-pitch -> variable-pitch
      (setq-local face-remapping-alist (append '(
                                                 (line-number fixed-pitch line-number)
                                                 (line-number-current-line fixed-pitch line-number-current-line)
                                                 (org-indent fixed-pitch org-indent org-hide)
                                                 (org-block fixed-pitch org-block)
                                                 (org-table fixed-pitch org-table)
                                                 (org-formula fixed-pitch org-formula)
                                                 (org-checkbox fixed-pitch org-checkbox)
                                                 (org-verbatim  fixed-pitch org-verbatim)
                                                 (org-special-keyword font-lock-comment-face fixed-pitch org-special-keyword)
                                                 )
                                               face-remapping-alist))
    ;; we are leaving variable-picht mode
    (setq-local face-remapping-alist nil)))

(advice-add 'variable-pitch-mode :after #'fb/variable-pitch-faces)
;; (advice-remove 'variable-pitch-mode  #'fb/variable-pitch-faces)


(defun fb/org-present-start ()
  "Start the current buffer in a presentation mode"
  ;; Tweak font sizes
  ;; (setq-local face-remapping-alist '(
  ;;                                    ;; (org-meta-line font-lock-comment-face fixed-pitch)
  ;;                                    ;; (org-superstar-leading org-hide)
  ;;                                    ;; (default (:height 1.5) variable-pitch)
  ;;                                    ;; (header-line (:height 4.0) variable-pitch)
  ;;                                    ;; (org-document-title (:height 1.75) org-document-title)
  ;;                                    ;; (org-code (:height 1.55) org-code fixed-pitch)
  ;;                                    ;; (org-verbatim (:height 1.55) org-verbatim)
  ;;                                    ;; (org-block (:height 1.25) org-block fixed-pitch)
  ;;                                    ;; (org-block-begin-line (:height 0.7) org-block-begin-)
  ;;                                                                                             ))
  (call-interactively 'variable-pitch-mode)
  (add-to-list 'face-remapping-alist '(org-block (:height 1.4) fixed-pitch org-block))
  (add-to-list 'face-remapping-alist '(org-code (:height 1.5) fixed-pitch org-code))
  (add-to-list 'face-remapping-alist '(org-verbatim (:height 1.5) fixed-pitch org-verbatim))
  (add-to-list 'face-remapping-alist '(org-formula (:height 1.5) fixed-pitch org-formula))
  (add-to-list 'face-remapping-alist '(org-table (:height 1.5) fixed-pitch org-table))
  (add-to-list 'face-remapping-alist '(org-block-begin-line (:height 0.7  :foreground "#FFFFFF") fixed-pitch org-block-begin-line))
  (add-to-list 'face-remapping-alist '(org-document-title (:height 2.0)  org-document-title))
  (add-to-list 'face-remapping-alist '(org-document-info (:height 1.4)  org-document-info))
  (org-present-big)
  ;; images are displayed
  (org-display-inline-images)
  ;; line numbers are hidden
  (setq display-line-numbers-type nil)
  (setq display-line-numbers nil)
  ;; small space at the top of the buffer
  (setq header-line-format " ")
  ;; Center the presentation and wrap lines
  (visual-fill-column-mode 1)
  ;; stop electric indent mode to avoid keybindings conflicts
  (electric-indent-mode 0)
  ;; Remove indentation of all blocks based on their level in the hierarchy
  (org-indent-mode -1)
  ;; set buffer to read only
  (org-present-read-only)
  ;; Disable flyspell
  (flyspell-mode -1)
  ;; go full screen
  (toggle-frame-fullscreen)
  ;; disable beacon
  (beacon-mode -1)
  ;; force normal mode
  (evil-force-normal-state)
  ;; hide the mode line
  (hide-mode-line-mode 1))

(defun fb/org-present-stop ()
  "Stop the current presentation mode"
  ;; Reset font customizations
  ;; (setq-local face-remapping-alist nil)
  (call-interactively 'variable-pitch-mode)
  (org-present-small)
  ;; Display line numbers
  (setq display-line-numbers-type 'relative)
  (setq display-line-numbers 'relative)
  ;; Clear the header line string so that it isn't displayed
  (setq header-line-format nil)

  ;; Stop displaying inline images
  (org-remove-inline-images)
  ;; Display buffer with normal layout
  (visual-fill-column-mode 0)
  ;; re-enable electric indent mode
  (electric-indent-mode 1)
  ;; Enable again indentation of all blocks
  (org-indent-mode 1)
  ;; set buffer to read/write
  (org-present-read-write)
  ;; Enable flyspell
  (flyspell-mode 1)
  ;; Exit full screen
  (toggle-frame-fullscreen)
  ;; enable beacon
  (beacon-mode 1)
  ;; show mode line
  (hide-mode-line-mode -1))

(use-package! visual-fill-column
  :defer t
  :custom
  (visual-fill-column-width 30)
  (visual-fill-column-center-text t))

(use-package! org-present
  :after org
  :defer t
  :config
  (setq org-present-text-scale 3)
  :init
  (add-hook 'org-present-mode-hook 'fb/org-present-start)
  (add-hook 'org-present-mode-quit-hook 'fb/org-present-stop))

(map!
 :mode org-mode
 :leader
 :desc "Start presentation"
 "t p" #'org-present)

(map! (:localleader
       (:map (org-mode-map)
             (:prefix ("v" . "verb")
              :desc "Run req, stay in current window"
              "r" #'verb-send-request-on-point-other-window-stay
              :desc "Run req, go to other window"
              "s" #'verb-send-request-on-point-other-window
              :desc "Run req, res in new buffer"
              "f" #'verb-send-request-on-point
              :desc "Kill all response buffers"
              "k" #'verb-kill-all-response-buffers
              :desc "Export request"
              "e" #'verb-export-request-on-point))))

(use-package org-modern-indent
  :config
  (add-hook 'org-mode-hook #'org-modern-indent-mode 90))

;; beacon highlights the line we are moving to
(use-package! beacon
  :custom
  (beacon-color "yellow")
  (beacon-blink-duration 1)
  (beacon-blink-when-point-moves-vertically t)
  (beacon-blink-when-point-moves-horizontally t))

;; (after! beacon
;;   (beacon-mode 1))

;; Auto save mode
(use-package! super-save
  :defer t
  :custom
  (auto-save-default nil)          ;; nil to switch off the built-in `auto-save-mode', maybe leave it t to have a backup!
  (super-save-exclude '(".gpg"))
  (super-save-remote-files nil)
  (super-save-auto-save-when-idle t)
  (super-save-idle-duration 3.0)
  (super-save-silent t)
  :config
  (add-to-list 'super-save-triggers 'evil-switch-to-windows-last-buffer)
  (add-to-list 'super-save-triggers 'persp-frame-switch)
  (add-to-list 'super-save-triggers 'find-file)
  (add-to-list 'super-save-triggers 'magit-status)
  (add-to-list 'super-save-triggers 'kill-current-buffer)
  :hook
  (after-init . super-save-mode))

;; Got it from https://github.com/seagle0128/doom-modeline/issues/122
(defun +toggle-keycast()
  (interactive)
  (if (member '("" keycast-mode-line " ") global-mode-string)
      (progn (setq global-mode-string (delete '("" keycast-mode-line " ") global-mode-string))
             (remove-hook 'pre-command-hook 'keycast--update)
             (message "Keycast OFF"))
    (add-to-list 'global-mode-string '("" keycast-mode-line " "))
    (add-hook 'pre-command-hook 'keycast--update t)
    (message "Keycast ON")))

(use-package! keycast
  :after doom-modeline
  :config
  (+toggle-keycast)
  ;;(setq keycast-mode-line-insert-after '(:eval (doom-modeline-format--main)))
  ;; (add-to-list 'global-mode-string '("" keycast-mode-line))
  ;; :hook
  ;; (doom-modeline-mode . keycast-mode-line-mode)
                                               )

;; (unless keycast-header-line-mode
;;   (keycast-header-line-mode))

(defun fb/hide-keycast ()
  (interactive)
  (keycast-header-line-mode -1))

(defun fb/enable-keycast ()
  (interactive)
  (keycast-header-line-mode 1))

;; (defun fb/get-frame-tab-name (&optional frame)
;;   "Return the string that names FRAME (a frame).  Default is selected frame."
;;   (unless frame (setq frame  (selected-frame)))
;;   (if (framep frame)
;;       (cdr (assq 'name (assq 'current-tab (assq 'tabs (frame-parameters frame)))))
;;     (error "Function `get-frame-tab-name': Argument not a frame: `%s'" frame)))

;; (defun fb/get-a-frame-by-tab-name (frame)
;;   "Return a frame, if any, named FRAME (a frame or a string).
;; If none, return nil.
;; If FRAME is a frame, it is returned."
;;   (cond ((framep frame) frame)
;;         ((stringp frame)
;;          (catch 'get-a-frame-found
;;            (dolist (fr (frame-list))
;;              (let ((frame-tab-name (fb/get-frame-tab-name fr)))
;;                (when (and frame-tab-name (string-match-p frame frame-tab-name))
;;                  (throw 'get-a-frame-found fr))))
;;            nil))
;;         (t (error
;;             "Function `get-frame-tab-name': Arg neither a string nor a frame: `%s'"
;;             frame))))

;; (defun fb/find-company-box-frame ()
;;   "Find the company box frame."
;;   (fb/get-a-frame-by-tab-name "\*company-box-[0-9]*\\*"))

;; (defun fb/find-company-box-doc-frame ()
;;   "Find the company box doc frame."
;;   (fb/get-a-frame-by-tab-name "\*company-box-[0-9]*doc\\*"))

;; (defun fb/disable-tab-bar-for-company-child-frame ()
;;   "Disable tab bar for company box frames."
;;   (interactive)
;;   (set-frame-parameter (fb/find-company-box-frame) 'tab-bar-lines 0)
;;   (set-frame-parameter (fb/find-company-box-doc-frame) 'tab-bar-lines 0))

;; (after! (:and keycast company-box)
;;   (add-hook 'company-box-mode-hook #'fb/disable-tab-bar-for-company-child-frame))

(map! :leader
        :desc "Translate (convert)"
        "s c" #'gt-translate)

(use-package! gt
  :defer t
  :custom
  (gt-langs '(en fr))
  :config
  (setq gt-default-translator
        (gt-translator
         :taker (gt-taker :text 'buffer :pick 'paragraph)
         :engines (list
                   (gt-deepl-engine :key (auth-source-pick-first-password :host "deepl") :pro nil)
                   (gt-google-engine)
                   (gt-bing-engine))
         :render (gt-buffer-render)))
  ;; Evil mode should be in emacs mode in the "Go Translate" buffer to be able to use the keybindings
  ;; (add-to-list 'evil-buffer-regexps '("gt-result" . emacs))
  )

(defun fb/zoom ()
  (interactive)
  (when (or (derived-mode-p 'prog-mode)
            (derived-mode-p 'text-mode))
    (zoom)))

(use-package! zoom
  :defer t
  :hook
  (doom-switch-window . fb/zoom)
  ;; (doom-switch-buffer . fb/zoom) ;; which-key is affected by this config
  ;; (window-configuration-change . fb/zoom) ;; which-key is affected by this config
  :custom
  (zoom-size '(0.618 . 0.618)))

(use-package! selection-highlight-mode
  :defer t
  :config (selection-highlight-mode))

;; (use-package! vertico-posframe
;;   :config
;;   (vertico-posframe-mode))

;; (defun fb/disable-vertico-posframe (fn &rest args)
;;   "Disable `vertico-posframe-mode' when the provided FN is called."
;;   (vertico-posframe-mode -1)
;;   (unwind-protect                   ;; This allow to protect the next from to exit completly from this function (eg with keyboard-quit function)
;;       (apply fn args)
;;     (vertico-posframe-mode 1)))

;; (defun fb/enable-vertico-buffer-mode (fn &rest args)
;;   "Enable `vertico-buffer-mode' when the provided FN is called."
;;   (vertico-buffer-mode 1)
;;   (unwind-protect                   ;; This allow to protect the next from to exit completly from this function (eg with keyboard-quit function)
;;       (apply fn args)
;;     (vertico-buffer-mode -1)))

;; ;; Disable vertico-posframe-mode when `consult-line' is called to not block the code preview
;; (advice-add 'consult-line :around #'fb/disable-vertico-posframe)

;; ;; Enable `vertico-buffer-mode' when using `consult-line'
;; (advice-add 'consult-line :around #'fb/enable-vertico-buffer-mode)

;; (defun advice-unadvice (sym)
;;   "Remove all advices from symbol SYM."
;;   (interactive "aFunction symbol: ")
;;   (advice-mapc (lambda (advice _props) (advice-remove sym advice)) sym))

;; (advice-unadvice 'consult-line)

(use-package! gptel
  :defer t
  :hook
  (gptel-post-stream . gptel-auto-scroll)
  :config
  (add-hook 'gptel-post-response-functions 'gptel-end-of-response)
  (setq-default gptel-model 'gemma3:latest                ;; default model
                gptel-backend (gptel-make-ollama          ;; only one model for now
                               "ollama"
                               :host "localhost:11434"
                               :key ""                    ;; gptel is asking for a key if not set here
                               :models '(mistral:latest gemma:2b llama3.1:latest llama3.2:latest gemma3:latest)
                               :stream t)
                gptel-max-tokens 800)
  (advice-add 'gptel-send :after #'evil-force-normal-state))

(defun fb/start-ollama ()
  "Start Ollama server in a subprocess."
  (interactive)
  (if (get-process "ollama")
      (message "Ollama already started")
    (when (start-process "ollama" "*ollama logs*" "ollama" "serve")
      (message "Ollama started, output is in *ollama logs* buffer"))))

(defun fb/stop-ollama ()
  "Stop Ollama server if one is running."
  (interactive)
  (let ((proc (get-process "ollama")))
    (if proc
        (if (shell-command (concat "kill " (number-to-string (process-id proc))))
            (message "Ollama stopped")
          (message "Ollama cannot be stopped"))
      (message "Ollama is not running"))))


(map! :leader
      :desc "Start Ollama server"
      "l z" #'fb/start-ollama
      :desc "Stop Ollama server"
      "l Z" #'fb/stop-ollama)

(use-package! blamer
  :defer 20
  :custom
  (blamer-idle-time 0.3)
  (blamer-min-offset 50)
  (blamer-author-formatter " ✎ %s ")
  (blamer-datetime-formatter "[%s]")
  (blamer-commit-formatter " ● %s")
  (blamer-max-commit-message-length 80)
  (blamer-uncommitted-changes-message  "NOT YET COMMITTED")
  ;; :custom-face
  ;; (blamer-face ((t :foreground "#7a88cf"
  ;;                   :background nil
  ;;                   :height 140
  ;;                   :italic t)))
  :config
  ;; (global-blamer-mode 1)
  )

;; (use-package! casual-dired
;;   :bind
;;   (:map dired-mode-map ("C-m" . 'casual-dired-tmenu)))

(use-package! separedit
  :custom
  (separedit-default-mode 'markdown-mode))

(map! :map (prog-mode-map minibuffer-local-map helpful-mode-map)
      "C-c '" #'separedit)

;; Expand and contract region available when pressing multiple times v or V in visual mode
(map!
 (:map 'override
  :v "v" #'er/expand-region
  :v "V" #'er/contract-region))

(map! :localleader
      :map (clojure-mode-map clojurescript-mode-map clojurec-mode-map)
      "e l" #'cider-eval-list-at-point
      :desc "Insert debug form"
      "d i" (lambda ()
              (interactive)
              (let* ((choices '(("#break from Cider"  . "#break ")
                                ("#dbg from Cider" . "#dbg ")
                                ("#p from Hashp"  . "#p ")
                                ("#bogus from Bogus"  . "#bogus ")))
                     (resp (alist-get
                            (consult--read choices :prompt "Choose debug form to insert: " :sort nil :require-match t)
                            choices nil nil 'equal)))
                (insert resp))))

(map! :leader
      :desc "Go to [test ⯇⯈ implementation] file"
      :n
      "p q" #'projectile-toggle-between-implementation-and-test)

;; (map!
;;  :n
;;  "S-<up>" #'windmove-up
;;  "S-<down>" #'windmove-down
;;  "S-<left>" #'windmove-left
;;  "S-<right>" #'windmove-right)

(map! (:localleader
       (:map (clojure-mode-map clojurescript-mode-map clojurec-mode-map)
             (:prefix ("k" . "kaocha test runner")
                      "t" #'kaocha-runner-run-test-at-point
                      "r" #'kaocha-runner-run-tests
                      "a" #'kaocha-runner-run-all-tests
                      "w" #'kaocha-runner-show-warnings
                      "h" #'kaocha-runner-hide-windows))))

;; record the position where `fb/eval-markers-new` was called
(defvar eval-markers-markers nil)

;; allow to mark a position
(defun fb/eval-markers-new ()
  "Save the current position for future evaluation with `fb/eval-markers-eval`."
  (interactive)
  (setf eval-markers-markers (point-marker))
  (message "Position is registered file[%s] line[%d]" (buffer-file-name) (line-number-at-pos)))

;; alow to evaluate a expression previously recorded with `fb/eval-markers-new`
(defun fb/eval-markers-eval ()
  "Evaluate the form registered previously with `fb/eval-markers-new`."
  (interactive)
  (let ((m eval-markers-markers))
    (with-current-buffer (marker-buffer m)
      (save-excursion
        (goto-char (marker-position m))
        (forward-sexp)
        (cider-eval-defun-at-point)))))

(map! :localleader
      :map (clojure-mode-map clojurescript-mode-map clojurec-mode-map)
      :desc "Mark exp"
      "e M" #'fb/eval-markers-new
      :desc "Eval exp at marker"
      "e m" #'fb/eval-markers-eval)

(defun fb/evil-normalize-all-buffers ()
  "Force a drop to normal state for all opened buffers."
  (dolist (buffer (buffer-list))
    (with-current-buffer buffer
      (unless (or (minibufferp) (eq evil-state 'emacs))
        (evil-force-normal-state))))
  (message "Dropped back to normal state in all buffers"))

(defvar fb/evil-normal-timer
  (run-with-idle-timer 30 t #'fb/evil-normalize-all-buffers)
  "Drop back to normal state after idle for 30 seconds.")

(sp-with-modes '(clojure-mode clojurescript-mode)
  (sp-local-pair "(" ")" :unless '(:rem sp-point-before-word-p sp-point-before-same-p))
  (sp-local-pair "(" ")" :unless '(sp-in-string-p sp-in-comment-p))
  (sp-local-pair "[" "]" :unless '(:rem sp-point-before-word-p sp-point-before-same-p))
  (sp-local-pair "[" "]" :unless '(sp-in-string-p sp-in-comment-p))
  (sp-local-pair "{" "}" :unless '(:rem sp-point-before-word-p sp-point-before-same-p))
  (sp-local-pair "{" "}" :unless '(sp-in-string-p sp-in-comment-p))
  )

(sp-with-modes '(emacs-lisp-mode)
  (sp-local-pair "(" ")" :unless '(:rem sp-point-before-word-p sp-point-before-same-p))
  (sp-local-pair "(" ")" :unless '(sp-in-string-p sp-in-comment-p)))

(map!
 :after embark
 :map minibuffer-local-map
 "<backtab>" (lambda () (interactive) (embark-select) (vertico-next)))

(map! :after consult
      :leader
      :desc "Flycheck for current buffer"
      "c z" #'consult-flycheck)

(defun fb/sort-words (reverse beg end)
      "Sort words in region alphabetically, in REVERSE if negative.
    Prefixed with negative \\[universal-argument], sorts in reverse.

    The variable `sort-fold-case' determines whether alphabetic case
    affects the sort order.

    See `sort-regexp-fields'."
      (interactive "*P\nr")
      (sort-regexp-fields reverse "\\w+" "\\&" beg end))

(defun fb/sort-symbols (reverse beg end)
      "Sort symbols in region alphabetically, in REVERSE if negative.
    See `sort-words'."
      (interactive "*P\nr")
      (sort-regexp-fields reverse "\\(\\sw\\|\\s_\\)+" "\\&" beg end))

(defun fb/toggle-lsp-cider ()
  "Toggle between Cider and LSP completion"
  (interactive)
  (if (member 'lsp-completion-at-point completion-at-point-functions)
      ;; LSP is enabled, must enable Cider
      (progn
        (remove-hook 'completion-at-point-functions #'lsp-completion-at-point t)
        (add-hook 'completion-at-point-functions #'cider-complete-at-point 0 t)
        (message "Cider completion enabled"))
    ;; Cider is enabled, must enable LSP
    (progn
      (remove-hook 'completion-at-point-functions #'cider-complete-at-point t)
      (add-hook 'completion-at-point-functions #'lsp-completion-at-point 0 t)
      (message "LSP completion enabled"))))

(defun insert-into-list (list el n)
  "Insert into list LIST an element EL at index N.

If N is 0, EL is inserted before the first element.

The resulting list is returned.  As the list contents is mutated
in-place, the old list reference does not remain valid."
  (let* ((padded-list (cons nil list))
         (c (nthcdr n padded-list)))
    (setcdr c (cons el (cdr c)))
    (cdr padded-list)))

(defun fb/cider+lsp-completion-setup ()
    "Add LSP and cider completions together"
    (interactive)
    (when (and (member 'lsp-completion-at-point completion-at-point-functions)
               (not (member 'cider-complete-at-point completion-at-point-functions)))
      (let ((position (cl-position #'lsp-completion-at-point completion-at-point-functions)))
        (progn
          (setq-local completion-at-point-functions (insert-into-list completion-at-point-functions #'cider-complete-at-point (1+ position)))
          (message "LSP and Cider completions setup done")))))

(defun fb/get-frame-tab-name (&optional frame)
  "Return the string that names FRAME (a frame).  Default is selected frame."
  (unless frame (setq frame  (selected-frame)))
  (if (framep frame)
      (cdr (assq 'name (assq 'current-tab (assq 'tabs (frame-parameters frame)))))
    (error "Function `get-frame-tab-name': Argument not a frame: `%s'" frame)))

(defun fb/get-a-frame-by-tab-name (frame)
  "Return a frame, if any, named FRAME (a frame or a string).
If none, return nil.
If FRAME is a frame, it is returned."
  (cond ((framep frame) frame)
        ((stringp frame)
         (catch 'get-a-frame-found
           (dolist (fr (frame-list))
             (let ((frame-tab-name (fb/get-frame-tab-name fr)))
               (when (and frame-tab-name (string-match-p frame frame-tab-name))
                 (throw 'get-a-frame-found fr))))
           nil))
        (t (error
            "Function `get-frame-tab-name': Arg neither a string nor a frame: `%s'"
            frame))))

(defun fb/find-company-box-frame ()
  "Find the company box frame."
  (fb/get-a-frame-by-tab-name "\*company-box-[0-9]*\\*"))

(defun fb/find-company-box-doc-frame ()
  "Find the company box doc frame."
  (fb/get-a-frame-by-tab-name "\*company-box-[0-9]*doc\\*"))

(defun fb/disable-tab-bar-for-company-child-frame ()
  "Disable tab bar for company box frames."
  (interactive)
  (set-frame-parameter (fb/find-company-box-frame) 'tab-bar-lines 0)
  (set-frame-parameter (fb/find-company-box-doc-frame) 'tab-bar-lines 0))

(after! (:and keycast company-box)
  (add-hook 'company-box-mode-hook #'fb/disable-tab-bar-for-company-child-frame))

(after! smartparens
  (add-hook 'minibuffer-setup-hook (lambda ()
                                      (smartparens-strict-mode -1))))

;; This syntax is to bind macros to keys
(map!
 :n
 "M-<down>" (concat ":m +1" (kbd "RET") "==")
 "M-<up>"   (concat ":m -2" (kbd "RET") "==")
 :v
 "M-<down>" (concat ":m '>+1" (kbd "RET") "gv=gv")
 "M-<up>"   (concat ":m '<-2" (kbd "RET") "gv=gv"))

;; This syntax is to bind macros to keys
(map!
 :n
 "z q" #'delete-window)

(advice-add 'hide-mode-line-mode :around (lambda (orig &optional args) nil))

;; do an advice on narrow-to-region
;; (advice-add 'narrow-to-region :after #'remove-overlays)

(defun fb/tty-only-buffer-display-options ()
  (interactive)
  (when (not (display-graphic-p))
    (smartparens-strict-mode -1)
    (+word-wrap-mode 1)))

(add-hook 'doom-switch-buffer-hook #'fb/tty-only-buffer-display-options)
